Regress; update binaries; Add error checking to build script; Check mrklin option in pgen; Fix passthroughs.
 On branch master
 Changes to be committed:
	modified:   bin/build
	modified:   hosts/pascaline/linux_X86/pcom
	modified:   hosts/pascaline/linux_X86/pgen
	modified:   hosts/pascaline/linux_X86/pint
	modified:   hosts/pascaline/linux_X86/pmach

1. Update binaries.

	modified:   regress_report.txt

1. Regress.

	modified:   source/AMD64/gcc/pgen.pas

1. Cover all options in plcopt.

2. Update mrklin flag.

	modified:   source/parcmd.pas

1. Do not set module option, its a value option and it confuses set/reset
processors.

	modified:   source/pcom.pas

1. Cover all options in plcopt.

2. Passthough options if set.

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -13,8 +13,14 @@
 #
 function compprog {
 
-    pc $1 $OPTIONS
-    cp $1 bin
+   pc $1 $OPTIONS
+   if [ $? -ne 0 ]; then
+
+      echo "*** Error: compile failed"
+      exit 1
+
+   fi
+   cp $1 bin
 
 }
 
@@ -22,6 +28,12 @@ OPTIONS=$2
 
 make clean
 make $1
+if [ $? -ne 0 ]; then
+
+   echo "*** Error: make failed"
+   exit 1
+
+fi
 compprog pc/pc
 compprog pc/hashtabr
 compprog pc/hashtabs
