Finalize cpcoms; finalize cpints; label p2 and p4 in regression; fix compare in testp5.
 Changes to be committed:
	modified:   bin/cpcoms
	modified:   bin/cpints

1. Add p5 error handling.

2. Fix p5 reference.

	modified:   bin/regress

1. Label p2 and p4 runs.

	modified:   bin/testp5

1. Fix compare file.

	modified:   p5

diff --git a/bin/cpcoms b/bin/cpcoms
--- a/bin/cpcoms
+++ b/bin/cpcoms
@@ -10,8 +10,16 @@ cpp -DSELF_COMPILE -DWRDSIZ64 -P -nostdinc -traditional-cpp source/pcom.pas sour
 # Compile pcom to intermediate code using its binary version.
 #
 echo Compiling pcom to intermediate code
-compile source/pcomm.mpp
-cat source/pcom.mpp.err
+compile source/pcom.mpp
+if [ $? -ne 0 ]
+then
+
+    echo "*** Compile failed"
+    cat source/pcom.mpp.err
+    exit 1
+
+fi
+
 #
 # Now run that code on the interpreter and have it compile itself
 # to intermediate again.
@@ -20,7 +28,7 @@ echo Running pcom to compile itself
 
 cat source/pcom.mpp.p6 source/pcom.mpp.pas > tmp.p6
 mv source/pcom.mpp.p6 source/pcom.mpp.p6.org
-cp tmp.p5 source/pcom.mpp.p6
+cp tmp.p6 source/pcom.mpp.p6
 echo > source/pcom.mpp.inp
 
 run source/pcom.mpp
@@ -43,4 +51,4 @@ else
     echo PASS
 fi
 echo
-#ls -l pcomm.dif
+#ls -l source/pcom.mpp.dif
diff --git a/bin/cpints b/bin/cpints
--- a/bin/cpints
+++ b/bin/cpints
@@ -11,21 +11,35 @@ cpp -DSELF_COMPILE -DWRDSIZ64 -P -nostdinc -traditional-cpp source/pint.pas sour
 #
 echo Compiling the ISO 7185 PAT
 compile standard_tests/iso7185pat
-cat standard_tests/iso7185pat.err
+if [ $? -ne 0 ]
+then
+
+    echo "*** Compile failed"
+    cat standard_tests/iso7185pat.err
+    exit 1
+
+fi
 #
 # Compile pint itself
 #
 echo Compiling pint to intermediate code
 compile source/pint.mpp
-cat source/pint.mpp.err
+if [ $? -ne 0 ]
+then
+
+    echo "*** Compile failed"
+    cat source/pint.mpp.err
+    exit 1
+
+fi
 #
 # Add the final target program (the pat) to the end of pint.
 # This means that the version of pint will read and interpret
 # this.
 #
-cat soruce/pint.mpp.p6 standard_tests/iso7185pat.p6 > tmp.p6
-rm /source/pint.mpp.p6
-mv tmp.p5 pintm.p5
+cat source/pint.mpp.p6 standard_tests/iso7185pat.p6 > source/tmp.p6
+rm source/pint.mpp.p6
+mv source/tmp.p6 source/pint.mpp.p6
 #
 # Create null input file
 #
