Added diffnolestrip script; fix run options; change runprt to use diffnolestrip; fix strip script.
With deference to Trevor, the isgnore stuff didn't really belong in diffnole.
That script compensates for line endings. The ignore instructions were moved
to a different file, the strip script.

 Changes to be committed:
	modified:   bin/diffnole

1. Moved the diff ignore instructions out to strip script.

	new file:   bin/diffnolestrip

1. This script now combines stripping and line ending fix.

	modified:   bin/run

1. Moved the options to the front of the packaged executable. This is because of
progressive command line parsing, a concept that is so friggin' complex I would
have to use diagrams and dolls to explain.

	modified:   bin/runprt

1. Changed to use diffnolestrip script above.

	modified:   bin/strip

1. Updated with current definitions and parameter/file checking.

	modified:   regress_report.txt
	modified:   standard_tests/iso7185prt1702A.dat
	modified:   standard_tests/iso7185prt1702b.dat
	modified:   standard_tests/iso7185prt1702c.dat
	modified:   standard_tests/iso7185prt1702d.dat
	modified:   standard_tests/iso7185prt1703.dat
	modified:   standard_tests/iso7185prt1704.dat
	modified:   standard_tests/iso7185prt1705.dat
	modified:   standard_tests/iso7185prt1706a.dat
	modified:   standard_tests/iso7185prt1706b.dat
	modified:   standard_tests/iso7185prt1708.dat
	modified:   standard_tests/iso7185prt1709.dat
	modified:   standard_tests/iso7185prt1710.dat
	modified:   standard_tests/iso7185prt1712.dat
	modified:   standard_tests/iso7185prt1713.dat
	modified:   standard_tests/iso7185prt1714.dat
	modified:   standard_tests/iso7185prt1715.dat
	modified:   standard_tests/iso7185prt1716.dat
	modified:   standard_tests/iso7185prt1719.dat
	modified:   standard_tests/iso7185prt1720.dat
	modified:   standard_tests/iso7185prt1721.dat
	modified:   standard_tests/iso7185prt1722.dat
	modified:   standard_tests/iso7185prt1723.dat
	modified:   standard_tests/iso7185prt1724.dat
	modified:   standard_tests/iso7185prt1727.dat
	modified:   standard_tests/iso7185prt1728.dat
	modified:   standard_tests/iso7185prt1730.dat
	modified:   standard_tests/iso7185prt1731.dat
	modified:   standard_tests/iso7185prt1732.dat
	modified:   standard_tests/iso7185prt1733.dat
	modified:   standard_tests/iso7185prt1734.dat
	modified:   standard_tests/iso7185prt1735.dat
	modified:   standard_tests/iso7185prt1736.dat
	modified:   standard_tests/iso7185prt1737.dat
	modified:   standard_tests/iso7185prt1738.dat
	modified:   standard_tests/iso7185prt1739.dat
	modified:   standard_tests/iso7185prt1740.dat
	modified:   standard_tests/iso7185prt1741.dat
	modified:   standard_tests/iso7185prt1743.dat
	modified:   standard_tests/iso7185prt1744.dat
	modified:   standard_tests/iso7185prt1745.dat
	modified:   standard_tests/iso7185prt1746A.dat
	modified:   standard_tests/iso7185prt1746b.dat
	modified:   standard_tests/iso7185prt1750.dat
	modified:   standard_tests/iso7185prt1751.dat
	modified:   standard_tests/iso7185prt1754.dat
	modified:   standard_tests/iso7185prt1755.dat
	modified:   standard_tests/iso7185prt1756.dat
	modified:   standard_tests/iso7185prt1757.dat
	modified:   standard_tests/iso7185prt1758a.dat
	modified:   standard_tests/iso7185prt1758b.dat
	modified:   standard_tests/iso7185prt1800.dat
	modified:   standard_tests/iso7185prt1811.dat
	modified:   standard_tests/iso7185prt1828.dat
	modified:   standard_tests/iso7185prt1834.dat
	modified:   standard_tests/iso7185prt1839.dat
	modified:   standard_tests/iso7185prt1840.dat
	modified:   standard_tests/iso7185prt1850.dat
	modified:   standard_tests/iso7185prt1851.dat
	modified:   standard_tests/iso7185prt1852.dat
	modified:   standard_tests/iso7185prt1909.dat
	modified:   standard_tests/iso7185prt1918.dat

1. These input files formerly contained a space or spaces. I have no idea
why that changed, but the files are irrelevant in any case.

diff --git a/bin/strip b/bin/strip
--- a/bin/strip
+++ b/bin/strip
@@ -1,9 +1,44 @@
 #
 # Strip decorations from compiled listing files
 #
+# This script is used to prepare listing files for comparision. It strips out
+# all of the compiler/interpreter information messages so that different
+# interpreters or compilers don't generate different output results.
+#
+
+if [ -z "$1" ]
+then
+
+   echo "*** Error: Missing parameter 1"
+   echo "*** s/b \"strip <file1> <file2>\""
+   exit 1
+
+fi
+
+if [ ! -f $1 ]
+then
+   echo "*** Error: Missing $1 file"
+   exit 1
+fi
+
+if [ -z "$2" ]
+then
+
+   echo "*** Error: Missing parameter 2"
+   echo "*** s/b \"strip <file1> <file2>\""
+   exit 1
+
+fi
+
 grep -v -e 'P. Pascal .*interpreter vs. .\..\.x' $1 | \
-grep -v -e 'P. Pascal .*interpreter vs. .\..' $1 | \
+grep -v -e 'P. Pascal .*interpreter vs. .\..' | \
+grep -v -e 'P. Pascal .*code generator vs. .\..' | \
+grep -v -e 'P. Pascal .*code generator vs. .\..\.x' | \
+grep -v -e 'P. Pascal .*compiler vs. .\..' | \
+grep -v -e 'P. Pascal .*compiler vs. .\..\.x' | \
 grep -v -e 'Assembling/loading program' | \
 grep -v -e 'loading program' | \
 grep -v -e 'Running program' | \
+grep -v -e 'Generating program' | \
+grep -v -e 'Program generation complete' | \
 grep -v -e 'program complete' > $2
