Ran regression; add input to run script package and pgen; refactor pascals.
 Changes to be committed:
	modified:   bin/run

1. Add input file ability for package and pgen mode.

	modified:   bin/testpascals

1. Refactor script to provide better output.

	modified:   bin/testprog

1. Cleanup temp files.

	modified:   regress_report.txt

1. Ran regression.

Notes:

Moving to replace testpascals and similar scripts with improved
testprog script.

diff --git a/bin/testpascals b/bin/testpascals
--- a/bin/testpascals
+++ b/bin/testpascals
@@ -9,12 +9,34 @@ compile $1 sample_programs/pascals
 # Run that with the input file appended to the intermediate/object
 #
 run $1 sample_programs/pascals.inp sample_programs/pascals
-#
-# Compare to reference
-#
-diffnole sample_programs/pascals.lst sample_programs/pascals.cmp > sample_programs/pascals.dif
-#
-# Show the file, so if the length is zero, it compared ok.
-#
-echo "Resulting diff file length should be zero for pass"
-wc -l sample_programs/pascals.dif
+if [ $? -eq 0 ]; then
+
+    #
+    # Compare to reference
+    #
+    strip sample_programs/pascals.lst tmp1
+    strip sample_programs/pascals.cmp tmp2
+    diff -B tmp1 tmp2 > sample_programs/pascals.dif
+    rm -f tmp1
+    rm -f tmp2
+    ls -l sample_programs/pascals.dif > tmp1
+    grep ".dif" tmp1
+    rm -f tmp1
+    ## pass if diff file is empty
+    if test -s sample_programs/pascals.dif
+    then
+        if [ "$noerrmsg" = "0" ]; then
+    		    
+            echo "*** FAIL"
+
+        fi
+        exit 1
+    else
+        echo "PASS"
+    fi
+
+else
+
+    exit 1
+
+fi
