Return error from runprt and pass in options; testprog returns error and prints; Fix sets in pcom.
 Changes to be committed:
	modified:   bin/runprt

1. Return error if run is not correct.

	modified:   bin/testprog

1. Return error if run does not compare.

	modified:   regress_report.txt

	modified:   source/pcom.pas

1. Change single value sets to give error and avoid range error.

diff --git a/bin/testprog b/bin/testprog
--- a/bin/testprog
+++ b/bin/testprog
@@ -176,5 +176,21 @@ if [ $? -eq 0 ]; then
     ls -l $progfile.dif > $progfile.tmp
     grep ".dif" $progfile.tmp
     rm -f $progfile.tmp
+    ## pass if diff file is empty
+    if test -s $progfile.dif
+    then
+        if [ "$noerrmsg" = "0" ]; then
+    		    
+            echo "*** FAIL"
+
+        fi
+        exit 1
+    else
+        echo "PASS"
+    fi
+
+else
+
+    exit 1
 
 fi
