Add options to cpcoms and cpints; refactor testp2 to strip dialog and print pass/fail.

diff --git a/bin/testp2 b/bin/testp2
--- a/bin/testp2
+++ b/bin/testp2
@@ -45,11 +45,23 @@ cp p2/pasint.lst p2/roman.lst
 #
 echo Comparing PAT result to reference
 diffnole p2/roman.lst p2/roman.cmp > p2/roman.dif
-#
-# Show the file, so if the length is zero, it compared ok.
-#
-echo Resulting diff file length should be zero for pass
-wc -l p2/roman.dif
+
+strip p2/roman.lst tmp1
+strip p2/roman.cmp tmp2
+diff -B tmp1 tmp2 > p2/roman.dif
+rm -f tmp1
+rm -f tmp2
+ls -l p2/roman.dif > tmp1
+grep ".dif" tmp1
+rm -f tmp1
+## pass if diff file is empty
+if test -s roman.dif
+then
+    echo "*** FAIL"
+    exit 1
+else
+    echo "PASS"
+fi
 
 rm -f p2/pcomp.inp
 rm -f p2/pasint.inp
